project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  google-analytics: "G-TXS3Q9H2N5"

